"""Compatibility wrapper for the refactored contracts module."""
from pathlib import Path

# Ensure src/ is in path for imports
from saaaaaa.utils.contracts import (  # noqa: F401, E402
    # V2 Enhanced Contracts (Pydantic-based)
    AnalysisInputV2,
    AnalysisOutputV2,
    BaseContract,
    DocumentMetadataV2,
    ExecutionContextV2,
    ProcessedTextV2,
    ContractValidationError,
    DataIntegrityError,
    FlowCompatibilityError,
    SystemConfigError,
    StructuredLogger,
    compute_content_digest,
    utc_now_iso,
    # V1 Contracts (TypedDict-based)
    AnalysisInputV1,
    AnalysisInputV1Optional,
    AnalysisOutputV1,
    AnalysisOutputV1Optional,
    AnalyzerProtocol,
    ContractMismatchError,
    DocumentLoaderProtocol,
    DocumentMetadataV1,
    DocumentMetadataV1Optional,
    ExecutionContextV1,
    ExecutionContextV1Optional,
    ProcessedTextV1,
    ProcessedTextV1Optional,
    SentenceCollection,
    TextDocument,
    TextProcessorProtocol,
    ensure_hashable,
    ensure_iterable_not_string,
    validate_contract,
    validate_mapping_keys,
)
from saaaaaa.utils.seed_factory import SeedFactory  # noqa: F401, E402

__all__ = [
    # V2 Enhanced Contracts
    "AnalysisInputV2",
    "AnalysisOutputV2",
    "BaseContract",
    "DocumentMetadataV2",
    "ExecutionContextV2",
    "ProcessedTextV2",
    "ContractValidationError",
    "DataIntegrityError",
    "FlowCompatibilityError",
    "SystemConfigError",
    "StructuredLogger",
    "compute_content_digest",
    "utc_now_iso",
    # V1 Contracts
    "AnalysisInputV1",
    "AnalysisInputV1Optional",
    "AnalysisOutputV1",
    "AnalysisOutputV1Optional",
    "AnalyzerProtocol",
    "ContractMismatchError",
    "DocumentLoaderProtocol",
    "DocumentMetadataV1",
    "DocumentMetadataV1Optional",
    "ExecutionContextV1",
    "ExecutionContextV1Optional",
    "ProcessedTextV1",
    "ProcessedTextV1Optional",
    "SeedFactory",
    "SentenceCollection",
    "TextDocument",
    "TextProcessorProtocol",
    "ensure_hashable",
    "ensure_iterable_not_string",
    "validate_contract",
    "validate_mapping_keys",
]
