"""Compatibility wrapper for Derek Beach CDAF framework."""
from pathlib import Path

# Ensure src/ is in path for imports
from saaaaaa.analysis.dereck_beach import (  # noqa: F401, E402
    AdaptivePriorCalculator,
    AuditResult,
    BayesFactorTable,
    BayesianCounterfactualAuditor,
    BayesianMechanismInference,
    BeachEvidentialTest,
    CDAFConfigSchema,
    CDAFException,
    CDAFFramework,
    CDAFProcessingError,
    CDAFValidationError,
    CausalExtractor,
    CausalInferenceSetup,
    CausalLink,
    ConfigLoader,
    DerekBeachProducer,
    EntityActivity,
    FinancialAuditor,
    GoalClassification,
    HierarchicalGenerativeModel,
    MechanismPartExtractor,
    MetaNode,
    OperationalizationAuditor,
    PDFProcessor,
    ReportingEngine,
)

__all__ = [
    "AdaptivePriorCalculator",
    "AuditResult",
    "BayesFactorTable",
    "BayesianCounterfactualAuditor",
    "BayesianMechanismInference",
    "BeachEvidentialTest",
    "CDAFConfigSchema",
    "CDAFException",
    "CDAFFramework",
    "CDAFProcessingError",
    "CDAFValidationError",
    "CausalExtractor",
    "CausalInferenceSetup",
    "CausalLink",
    "ConfigLoader",
    "DerekBeachProducer",
    "EntityActivity",
    "FinancialAuditor",
    "GoalClassification",
    "HierarchicalGenerativeModel",
    "MechanismPartExtractor",
    "MetaNode",
    "OperationalizationAuditor",
    "PDFProcessor",
    "ReportingEngine",
]
