# Generated 166 calibrations

from dataclasses import dataclass
from typing import Dict, Tuple, Optional

# Calibration version for tracking changes
CALIBRATION_VERSION = "1.0.0"


class MissingCalibrationError(Exception):
    """Raised when a method lacks explicit calibration for its execution context.
    
    This error enforces the policy that no method may execute without a rigorously
    defined calibration profile. Silent fallbacks to generic defaults are prohibited.
    
    Attributes:
        method_fqn: Fully qualified name of the method (ClassName.method_name)
        context: Execution context dict with question_id, document_type, etc.
    """
    
    def __init__(self, method_fqn: str, context: Optional[Dict] = None):
        self.method_fqn = method_fqn
        self.context = context or {}
        
        context_str = ", ".join(f"{k}={v}" for k, v in self.context.items() if v)
        msg = f"Missing calibration for method '{method_fqn}'"
        if context_str:
            msg += f" in context [{context_str}]"
        msg += ". Execution blocked - explicit calibration required."
        
        super().__init__(msg)


@dataclass(frozen=True)
class MethodCalibration:
    score_min: float
    score_max: float
    min_evidence_snippets: int
    max_evidence_snippets: int
    contradiction_tolerance: float
    uncertainty_penalty: float
    aggregation_weight: float
    sensitivity: float
    requires_numeric_support: bool
    requires_temporal_support: bool
    requires_source_provenance: bool
    
    # Additional metadata for calibration tracking
    safe_default_allowed: bool = False  # Must be explicitly True to allow fallback
    document_type: Optional[str] = None  # "plan_desarrollo_municipal", "politica_publica", etc.

    def is_default_like(self) -> bool:
        if self.score_min == 0 and self.score_max == 1 and self.aggregation_weight == 1.0:
            if self.min_evidence_snippets <= 1 and self.contradiction_tolerance >= 0.9:
                return True
        return False

CALIBRATIONS: Dict[Tuple[str, str], MethodCalibration] = {
    ("AdvancedDAGValidator", "_calculate_bayesian_posterior"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("AdvancedDAGValidator", "_calculate_confidence_interval"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("AdvancedDAGValidator", "_calculate_statistical_power"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("AdvancedDAGValidator", "_perform_sensitivity_analysis_internal"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("AdvancedDAGValidator", "calculate_acyclicity_pvalue"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("AdvancedDAGValidator", "get_graph_stats"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("AdvancedSemanticChunker", "_infer_pdq_context"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianConfidenceCalculator", "calculate_posterior"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=18,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.25,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianEvidenceScorer", "_calculate_shannon_entropy"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianEvidenceScorer", "compute_evidence_score"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=18,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.25,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianMechanismInference", "_aggregate_bayesian_confidence"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=18,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.25,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianMechanismInference", "_build_transition_matrix"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianMechanismInference", "_calculate_type_transition_prior"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianMechanismInference", "_classify_mechanism_type"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianMechanismInference", "_infer_activity_sequence"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianMechanismInference", "_test_necessity"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianMechanismInference", "_test_sufficiency"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianMechanismInference", "infer_mechanisms"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianNumericalAnalyzer", "_classify_evidence_strength"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=18,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.25,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianNumericalAnalyzer", "_compute_coherence"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianNumericalAnalyzer", "compare_policies"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianNumericalAnalyzer", "evaluate_policy_metric"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=18,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.25,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BeachEvidentialTest", "apply_test_logic"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BeachEvidentialTest", "classify_test"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CDAFFramework", "_audit_causal_coherence"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CDAFFramework", "_generate_causal_model_json"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CDAFFramework", "_generate_dnp_compliance_report"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CDAFFramework", "_generate_extraction_report"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CDAFFramework", "_validate_dnp_compliance"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("CDAFFramework", "process_document"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalExtractor", "_add_node_to_graph"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalExtractor", "_calculate_confidence"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalExtractor", "_classify_goal_type"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalExtractor", "_extract_causal_justifications"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalExtractor", "_extract_causal_links"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalExtractor", "_extract_goal_text"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalExtractor", "_extract_goals"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalExtractor", "extract_causal_hierarchy"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalInferenceSetup", "_get_dynamics_pattern"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalInferenceSetup", "assign_probative_value"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalInferenceSetup", "classify_goal_dynamics"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalInferenceSetup", "identify_failure_points"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("FinancialAuditor", "_calculate_sufficiency"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("FinancialAuditor", "_detect_allocation_gaps"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("FinancialAuditor", "_match_goal_to_budget"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("FinancialAuditor", "trace_financial_allocation"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    
    # =========================================================================
    # SMART POLICY CHUNKS (SPC) PHASE ONE CALIBRATIONS
    # =========================================================================
    ("StrategicChunkingSystem", "generate_smart_chunks"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=5,
        max_evidence_snippets=50,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.25,
        aggregation_weight=1.5,
        sensitivity=0.90,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
        safe_default_allowed=False,
        document_type="plan_desarrollo_municipal"
    ),
    ("StrategicChunkingSystem", "semantic_search_with_rerank"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=10,
        contradiction_tolerance=0.10,
        uncertainty_penalty=0.20,
        aggregation_weight=1.3,
        sensitivity=0.92,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
        safe_default_allowed=False,
        document_type="plan_desarrollo_municipal"
    ),
    ("StrategicChunkingSystem", "evaluate_numerical_consistency"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.30,
        aggregation_weight=1.4,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
        safe_default_allowed=False,
        document_type="plan_desarrollo_municipal"
    ),
    ("StrategicChunkingSystem", "_attach_canonical_evidence"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=5,
        max_evidence_snippets=30,
        contradiction_tolerance=0.12,
        uncertainty_penalty=0.28,
        aggregation_weight=1.35,
        sensitivity=0.88,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
        safe_default_allowed=False,
        document_type="plan_desarrollo_municipal"
    ),
    ("StrategicChunkingSystem", "_validate_strategic_integrity"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.08,
        uncertainty_penalty=0.35,
        aggregation_weight=1.25,
        sensitivity=0.93,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
        safe_default_allowed=False,
        document_type="plan_desarrollo_municipal"
    ),
    ("StrategicChunkingSystem", "_intelligent_deduplication"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.20,
        uncertainty_penalty=0.15,
        aggregation_weight=1.1,
        sensitivity=0.85,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=False,
        safe_default_allowed=True,
        document_type="plan_desarrollo_municipal"
    ),
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("IndustrialPolicyProcessor", "_analyze_causal_dimensions"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("IndustrialPolicyProcessor", "_build_point_patterns"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("IndustrialPolicyProcessor", "_compile_pattern_registry"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("IndustrialPolicyProcessor", "_construct_evidence_bundle"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.25,
        aggregation_weight=0.9,
        sensitivity=0.8,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("IndustrialPolicyProcessor", "_extract_point_evidence"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.25,
        aggregation_weight=0.9,
        sensitivity=0.8,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("IndustrialPolicyProcessor", "_match_patterns_in_sentences"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("IndustrialPolicyProcessor", "process"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("MechanismPartExtractor", "_calculate_ea_confidence"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("MechanismPartExtractor", "_find_action_verb"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("MechanismPartExtractor", "_find_subject_entity"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("MechanismPartExtractor", "_validate_entity_activity"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("MechanismPartExtractor", "extract_entity_activity"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("MechanismTypeConfig", "check_sum_to_one"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("MunicipalOntology", "__init__"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("OperationalizationAuditor", "_audit_systemic_risk"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("OperationalizationAuditor", "_generate_optimal_remediations"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("OperationalizationAuditor", "_perform_counterfactual_budget_check"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("OperationalizationAuditor", "audit_evidence_traceability"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("OperationalizationAuditor", "bayesian_counterfactual_audit"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_analyze_funding_sources"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_assess_financial_sustainability"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_bayesian_risk_inference"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_classify_entity_type"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_classify_tables"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_clean_dataframe"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_consolidate_entities"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_deduplicate_tables"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_extract_financial_amounts"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_extract_from_budget_table"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_extract_from_responsibility_tables"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_find_outcome_mentions"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_find_product_mentions"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_generate_optimal_remediations"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_identify_causal_edges"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_identify_causal_nodes"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_identify_funding_source"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_indicator_to_dict"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_is_likely_header"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_reconstruct_fragmented_tables"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_score_entity_specificity"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.25,
        aggregation_weight=0.9,
        sensitivity=0.8,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "analyze_financial_feasibility"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "analyze_municipal_plan"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "construct_causal_dag"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "extract_tables"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "generate_recommendations"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "identify_responsible_entities"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PerformanceAnalyzer", "_calculate_throughput_metrics"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PerformanceAnalyzer", "_detect_bottlenecks"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PerformanceAnalyzer", "_generate_recommendations"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyAnalysisEmbedder", "_extract_numerical_values"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyAnalysisEmbedder", "_filter_by_pdq"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyAnalysisEmbedder", "compare_policy_interventions"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyAnalysisEmbedder", "semantic_search"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_are_comparable_claims"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_are_conflicting_allocations"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_build_knowledge_graph"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_calculate_confidence_interval"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_calculate_contradiction_entropy"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_calculate_global_semantic_coherence"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_calculate_graph_fragmentation"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_calculate_numerical_divergence"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_calculate_objective_alignment"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_calculate_severity"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_calculate_similarity"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_calculate_syntactic_complexity"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_classify_contradiction"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_detect_logical_incompatibilities"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_detect_numerical_inconsistencies"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_detect_resource_conflicts"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_detect_semantic_contradictions"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_detect_temporal_conflicts"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_determine_relation_type"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_determine_semantic_role"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_extract_policy_statements"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_extract_quantitative_claims"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_extract_resource_mentions"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_extract_temporal_markers"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_generate_embeddings"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_generate_resolution_recommendations"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_get_context_window"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_get_dependency_depth"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_get_domain_weight"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_get_graph_statistics"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_has_logical_conflict"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_identify_dependencies"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_parse_number"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_statistical_significance_test"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_suggest_resolutions"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "detect"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyTextProcessor", "extract_contextual_window"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyTextProcessor", "normalize_unicode"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyTextProcessor", "segment_into_sentences"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("SemanticAnalyzer", "_calculate_semantic_complexity"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("SemanticAnalyzer", "_classify_cross_cutting_themes"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("SemanticAnalyzer", "_classify_policy_domain"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("SemanticAnalyzer", "_classify_value_chain_link"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("SemanticAnalyzer", "_process_segment"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("SemanticAnalyzer", "_vectorize_segments"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("SemanticAnalyzer", "extract_semantic_cube"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("SemanticProcessor", "_detect_table"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TemporalLogicVerifier", "_build_timeline"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("TemporalLogicVerifier", "_check_deadline_constraints"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("TemporalLogicVerifier", "_classify_temporal_type"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("TemporalLogicVerifier", "_extract_resources"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("TemporalLogicVerifier", "_has_temporal_conflict"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("TemporalLogicVerifier", "_parse_temporal_marker"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("TemporalLogicVerifier", "verify_temporal_consistency"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("TeoriaCambio", "_encontrar_caminos_completos"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TeoriaCambio", "_es_conexion_valida"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TeoriaCambio", "_execute_generar_sugerencias_internas"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TeoriaCambio", "_extraer_categorias"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TeoriaCambio", "_generar_sugerencias_internas"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TeoriaCambio", "_validar_orden_causal"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TeoriaCambio", "construir_grafo_causal"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TeoriaCambio", "validacion_completa"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TextMiningEngine", "_analyze_link_text"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TextMiningEngine", "_assess_risks"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TextMiningEngine", "_generate_interventions"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TextMiningEngine", "_identify_critical_links"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TextMiningEngine", "diagnose_critical_links"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    # SPC (Smart Policy Chunks) Ingestion - Canonical Phase-One
    ("StrategicChunkingSystem", "process_document"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=5,
        max_evidence_snippets=50,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.25,
        aggregation_weight=1.5,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
        safe_default_allowed=True,
        document_type="plan_desarrollo_municipal",
    ),
    ("CausalChainAnalyzer", "extract_causal_chains"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=25,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.35,
        aggregation_weight=1.3,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
        document_type="plan_desarrollo_municipal",
    ),
    ("KnowledgeGraphBuilder", "build_graph"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=30,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.3,
        aggregation_weight=1.2,
        sensitivity=0.85,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
        document_type="plan_desarrollo_municipal",
    ),
    ("TopicModeler", "infer_topics"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.2,
        uncertainty_penalty=0.2,
        aggregation_weight=1.0,
        sensitivity=0.8,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=False,
        safe_default_allowed=True,
        document_type="plan_desarrollo_municipal",
    ),
    ("ArgumentAnalyzer", "analyze_arguments"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
        document_type="plan_desarrollo_municipal",
    ),
    ("TemporalAnalyzer", "analyze_temporal_dynamics"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.25,
        aggregation_weight=1.2,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=True,
        requires_source_provenance=True,
        document_type="plan_desarrollo_municipal",
    ),
    ("DiscourseAnalyzer", "analyze_discourse"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
        document_type="plan_desarrollo_municipal",
    ),
    ("StrategicIntegrator", "integrate_analyses"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=5,
        max_evidence_snippets=40,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=1.4,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
        safe_default_allowed=True,
        document_type="plan_desarrollo_municipal",
    ),
}

def get_calibration_hash() -> str:
    """Compute deterministic hash of all calibrations for versioning.
    
    Returns:
        SHA256 hex digest of calibration registry
    """
    import hashlib
    import json
    
    # Serialize all calibrations to stable JSON
    calib_data = {}
    for (class_name, method_name), calib in sorted(CALIBRATIONS.items()):
        key = f"{class_name}.{method_name}"
        calib_data[key] = {
            "score_min": calib.score_min,
            "score_max": calib.score_max,
            "min_evidence_snippets": calib.min_evidence_snippets,
            "max_evidence_snippets": calib.max_evidence_snippets,
            "contradiction_tolerance": calib.contradiction_tolerance,
            "uncertainty_penalty": calib.uncertainty_penalty,
            "aggregation_weight": calib.aggregation_weight,
            "sensitivity": calib.sensitivity,
            "requires_numeric_support": calib.requires_numeric_support,
            "requires_temporal_support": calib.requires_temporal_support,
            "requires_source_provenance": calib.requires_source_provenance,
            "safe_default_allowed": calib.safe_default_allowed,
        }
    
    calib_json = json.dumps(calib_data, sort_keys=True)
    return hashlib.sha256(calib_json.encode("utf-8")).hexdigest()


def resolve_calibration(class_name: str, method_name: str, strict: bool = True) -> Optional[MethodCalibration]:
    """Resolve base calibration for a method.
    
    This returns the base calibration. For context-aware calibration,
    use resolve_contextual_calibration from calibration_context module.
    
    Args:
        class_name: Class containing the method
        method_name: Method name  
        strict: If True, raise MissingCalibrationError when calibration not found
        
    Returns:
        MethodCalibration or None (if strict=False and not found)
        
    Raises:
        MissingCalibrationError: If strict=True and calibration not found
    """
    key = (class_name, method_name)
    calib = CALIBRATIONS.get(key)
    
    if calib is None and strict:
        method_fqn = f"{class_name}.{method_name}"
        raise MissingCalibrationError(method_fqn, {"resolution": "base"})
    
    return calib


def resolve_calibration_with_context(
    class_name: str,
    method_name: str,
    question_id: Optional[str] = None,
    policy_area: Optional[str] = None,
    unit_of_analysis: Optional[str] = None,
    method_position: int = 0,
    total_methods: int = 1,
) -> Optional[MethodCalibration]:
    """Resolve calibration with contextual refinements.
    
    Args:
        class_name: Class containing the method
        method_name: Method name
        question_id: Question identifier (e.g., "D1Q1", "D6Q3")
        policy_area: Policy domain (fiscal, social, health, etc.)
        unit_of_analysis: Analysis type (baseline_gap, indicator, etc.)
        method_position: Position in method sequence (0-indexed)
        total_methods: Total methods in sequence
        
    Returns:
        Context-aware calibration, or None if no base calibration exists
        
    Example:
        >>> calib = resolve_calibration_with_context(
        ...     "BayesianEvidenceScorer",
        ...     "compute_evidence_score",
        ...     question_id="D1Q1",
        ...     policy_area="fiscal"
        ... )
    """
    # Get base calibration
    base_calib = resolve_calibration(class_name, method_name)
    if base_calib is None:
        return None
    
    # Import here to avoid circular dependency
    from .calibration_context import (
        CalibrationContext,
        PolicyArea,
        UnitOfAnalysis,
        resolve_contextual_calibration,
        infer_context_from_question_id,
    )
    
    # Build context
    if question_id:
        context = infer_context_from_question_id(question_id)
    else:
        context = CalibrationContext(
            question_id="unknown",
            dimension=0,
            question_num=0,
        )
    
    # Apply additional context overrides
    if policy_area:
        try:
            area_enum = PolicyArea(policy_area.lower())
            context = context.with_policy_area(area_enum)
        except (ValueError, AttributeError):
            pass  # Keep default if invalid
    
    if unit_of_analysis:
        try:
            unit_enum = UnitOfAnalysis(unit_of_analysis.lower())
            context = context.with_unit_of_analysis(unit_enum)
        except (ValueError, AttributeError):
            pass  # Keep default if invalid
    
    # Set method position
    if total_methods > 1:
        context = context.with_method_position(method_position, total_methods)
    
    # Resolve with context
    return resolve_contextual_calibration(base_calib, context)
