# Generated 166 calibrations

from dataclasses import dataclass
from typing import Dict, Tuple, Optional

@dataclass(frozen=True)
class MethodCalibration:
    score_min: float
    score_max: float
    min_evidence_snippets: int
    max_evidence_snippets: int
    contradiction_tolerance: float
    uncertainty_penalty: float
    aggregation_weight: float
    sensitivity: float
    requires_numeric_support: bool
    requires_temporal_support: bool
    requires_source_provenance: bool

    def is_default_like(self) -> bool:
        if self.score_min == 0 and self.score_max == 1 and self.aggregation_weight == 1.0:
            if self.min_evidence_snippets <= 1 and self.contradiction_tolerance >= 0.9:
                return True
        return False

CALIBRATIONS: Dict[Tuple[str, str], MethodCalibration] = {
    ("AdvancedDAGValidator", "_calculate_bayesian_posterior"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("AdvancedDAGValidator", "_calculate_confidence_interval"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("AdvancedDAGValidator", "_calculate_statistical_power"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("AdvancedDAGValidator", "_perform_sensitivity_analysis_internal"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("AdvancedDAGValidator", "calculate_acyclicity_pvalue"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("AdvancedDAGValidator", "get_graph_stats"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("AdvancedSemanticChunker", "_infer_pdq_context"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianConfidenceCalculator", "calculate_posterior"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=18,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.25,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianEvidenceScorer", "_calculate_shannon_entropy"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianEvidenceScorer", "compute_evidence_score"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=18,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.25,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianMechanismInference", "_aggregate_bayesian_confidence"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=18,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.25,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianMechanismInference", "_build_transition_matrix"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianMechanismInference", "_calculate_type_transition_prior"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianMechanismInference", "_classify_mechanism_type"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianMechanismInference", "_infer_activity_sequence"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianMechanismInference", "_test_necessity"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianMechanismInference", "_test_sufficiency"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianMechanismInference", "infer_mechanisms"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianNumericalAnalyzer", "_classify_evidence_strength"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=18,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.25,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianNumericalAnalyzer", "_compute_coherence"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianNumericalAnalyzer", "compare_policies"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BayesianNumericalAnalyzer", "evaluate_policy_metric"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=18,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.25,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BeachEvidentialTest", "apply_test_logic"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("BeachEvidentialTest", "classify_test"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CDAFFramework", "_audit_causal_coherence"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CDAFFramework", "_generate_causal_model_json"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CDAFFramework", "_generate_dnp_compliance_report"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CDAFFramework", "_generate_extraction_report"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CDAFFramework", "_validate_dnp_compliance"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("CDAFFramework", "process_document"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalExtractor", "_add_node_to_graph"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalExtractor", "_calculate_confidence"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalExtractor", "_classify_goal_type"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalExtractor", "_extract_causal_justifications"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalExtractor", "_extract_causal_links"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalExtractor", "_extract_goal_text"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalExtractor", "_extract_goals"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalExtractor", "extract_causal_hierarchy"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalInferenceSetup", "_get_dynamics_pattern"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalInferenceSetup", "assign_probative_value"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalInferenceSetup", "classify_goal_dynamics"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("CausalInferenceSetup", "identify_failure_points"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("FinancialAuditor", "_calculate_sufficiency"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("FinancialAuditor", "_detect_allocation_gaps"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("FinancialAuditor", "_match_goal_to_budget"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("FinancialAuditor", "trace_financial_allocation"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("IndustrialPolicyProcessor", "_analyze_causal_dimensions"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("IndustrialPolicyProcessor", "_build_point_patterns"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("IndustrialPolicyProcessor", "_compile_pattern_registry"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("IndustrialPolicyProcessor", "_construct_evidence_bundle"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.25,
        aggregation_weight=0.9,
        sensitivity=0.8,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("IndustrialPolicyProcessor", "_extract_point_evidence"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.25,
        aggregation_weight=0.9,
        sensitivity=0.8,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("IndustrialPolicyProcessor", "_match_patterns_in_sentences"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("IndustrialPolicyProcessor", "process"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("MechanismPartExtractor", "_calculate_ea_confidence"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("MechanismPartExtractor", "_find_action_verb"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("MechanismPartExtractor", "_find_subject_entity"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("MechanismPartExtractor", "_validate_entity_activity"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("MechanismPartExtractor", "extract_entity_activity"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("MechanismTypeConfig", "check_sum_to_one"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("MunicipalOntology", "__init__"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("OperationalizationAuditor", "_audit_systemic_risk"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("OperationalizationAuditor", "_generate_optimal_remediations"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("OperationalizationAuditor", "_perform_counterfactual_budget_check"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("OperationalizationAuditor", "audit_evidence_traceability"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("OperationalizationAuditor", "bayesian_counterfactual_audit"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_analyze_funding_sources"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_assess_financial_sustainability"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_bayesian_risk_inference"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_classify_entity_type"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_classify_tables"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_clean_dataframe"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_consolidate_entities"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_deduplicate_tables"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_extract_financial_amounts"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_extract_from_budget_table"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_extract_from_responsibility_tables"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_find_outcome_mentions"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_find_product_mentions"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_generate_optimal_remediations"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_identify_causal_edges"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_identify_causal_nodes"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_identify_funding_source"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_indicator_to_dict"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_is_likely_header"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_reconstruct_fragmented_tables"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "_score_entity_specificity"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.25,
        aggregation_weight=0.9,
        sensitivity=0.8,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "analyze_financial_feasibility"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "analyze_municipal_plan"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "construct_causal_dag"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "extract_tables"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "generate_recommendations"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PDETMunicipalPlanAnalyzer", "identify_responsible_entities"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PerformanceAnalyzer", "_calculate_throughput_metrics"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PerformanceAnalyzer", "_detect_bottlenecks"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PerformanceAnalyzer", "_generate_recommendations"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyAnalysisEmbedder", "_extract_numerical_values"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyAnalysisEmbedder", "_filter_by_pdq"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyAnalysisEmbedder", "compare_policy_interventions"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyAnalysisEmbedder", "semantic_search"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_are_comparable_claims"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_are_conflicting_allocations"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_build_knowledge_graph"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_calculate_confidence_interval"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_calculate_contradiction_entropy"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_calculate_global_semantic_coherence"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_calculate_graph_fragmentation"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_calculate_numerical_divergence"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_calculate_objective_alignment"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_calculate_severity"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_calculate_similarity"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_calculate_syntactic_complexity"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_classify_contradiction"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_detect_logical_incompatibilities"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_detect_numerical_inconsistencies"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_detect_resource_conflicts"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_detect_semantic_contradictions"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_detect_temporal_conflicts"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_determine_relation_type"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_determine_semantic_role"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_extract_policy_statements"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_extract_quantitative_claims"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_extract_resource_mentions"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_extract_temporal_markers"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_generate_embeddings"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_generate_resolution_recommendations"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_get_context_window"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_get_dependency_depth"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_get_domain_weight"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_get_graph_statistics"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_has_logical_conflict"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_identify_dependencies"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_parse_number"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_statistical_significance_test"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "_suggest_resolutions"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyContradictionDetector", "detect"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=20,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.3,
        aggregation_weight=1.1,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyTextProcessor", "extract_contextual_window"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyTextProcessor", "normalize_unicode"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("PolicyTextProcessor", "segment_into_sentences"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("SemanticAnalyzer", "_calculate_semantic_complexity"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.85,
        requires_numeric_support=True,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("SemanticAnalyzer", "_classify_cross_cutting_themes"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("SemanticAnalyzer", "_classify_policy_domain"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("SemanticAnalyzer", "_classify_value_chain_link"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("SemanticAnalyzer", "_process_segment"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("SemanticAnalyzer", "_vectorize_segments"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("SemanticAnalyzer", "extract_semantic_cube"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("SemanticProcessor", "_detect_table"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TemporalLogicVerifier", "_build_timeline"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("TemporalLogicVerifier", "_check_deadline_constraints"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("TemporalLogicVerifier", "_classify_temporal_type"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("TemporalLogicVerifier", "_extract_resources"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("TemporalLogicVerifier", "_has_temporal_conflict"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("TemporalLogicVerifier", "_parse_temporal_marker"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("TemporalLogicVerifier", "verify_temporal_consistency"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=4,
        max_evidence_snippets=25,
        contradiction_tolerance=0.0,
        uncertainty_penalty=0.35,
        aggregation_weight=1.2,
        sensitivity=0.95,
        requires_numeric_support=False,
        requires_temporal_support=True,
        requires_source_provenance=True,
    ),
    ("TeoriaCambio", "_encontrar_caminos_completos"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TeoriaCambio", "_es_conexion_valida"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TeoriaCambio", "_execute_generar_sugerencias_internas"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TeoriaCambio", "_extraer_categorias"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TeoriaCambio", "_generar_sugerencias_internas"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TeoriaCambio", "_validar_orden_causal"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TeoriaCambio", "construir_grafo_causal"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TeoriaCambio", "validacion_completa"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=2,
        max_evidence_snippets=15,
        contradiction_tolerance=0.1,
        uncertainty_penalty=0.2,
        aggregation_weight=0.9,
        sensitivity=0.75,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TextMiningEngine", "_analyze_link_text"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TextMiningEngine", "_assess_risks"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TextMiningEngine", "_generate_interventions"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=1,
        max_evidence_snippets=10,
        contradiction_tolerance=0.15,
        uncertainty_penalty=0.15,
        aggregation_weight=0.6,
        sensitivity=0.65,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TextMiningEngine", "_identify_critical_links"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
    ("TextMiningEngine", "diagnose_critical_links"): MethodCalibration(
        score_min=0.0, score_max=1.0,
        min_evidence_snippets=3,
        max_evidence_snippets=20,
        contradiction_tolerance=0.05,
        uncertainty_penalty=0.3,
        aggregation_weight=1.0,
        sensitivity=0.9,
        requires_numeric_support=False,
        requires_temporal_support=False,
        requires_source_provenance=True,
    ),
}

def resolve_calibration(class_name: str, method_name: str) -> Optional[MethodCalibration]:
    key = (class_name, method_name)
    return CALIBRATIONS.get(key)
